version: "3.7"
services:
  rb-theron-gazebo:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.2.0
    environment:
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      ROS_DOMAIN_ID: 40
      ROBOT_ID: robot_a
      ROBOT_DESCRIPTION_FILE: dual_laser.urdf.xacro
      POS_X: 0.0
      POS_Y: 0.0
      POS_Z: 0.1
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    runtime: nvidia
    network_mode: host

  rb-theron-rviz:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.2.0
    environment:
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      ROS_DOMAIN_ID: 40
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ./config/default.rviz
        target: /config/default.rviz
        read_only: true
    command: rviz2 -d /config/default.rviz --ros-args -p use_sim_time:=true
    runtime: nvidia
    network_mode: host

  rb-theron-map-server:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.2.0
    environment:
      ROS_DOMAIN_ID: 40
      ROS_BU_PKG: rb_theron_localization
      ROS_BU_LAUNCH: map_server.launch.py
    network_mode: host

  rb-theron-laser-merger:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.2.0
    environment:
      ROS_DOMAIN_ID: 40
      ROBOT_ID: robot_a
      ROS_BU_PKG: rb_theron_localization
      ROS_BU_LAUNCH: merge_laser.launch.py
    network_mode: host

  rb-theron-localization:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.2.0
    environment:
      ROS_DOMAIN_ID: 40
      ROBOT_ID: robot_a
      ROS_BU_PKG: rb_theron_localization
      ROS_BU_LAUNCH: localization.launch.py
    network_mode: host

  rb-theron-navigation:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.2.0
    environment:
      ROS_DOMAIN_ID: 40
      ROBOT_ID: robot_a
      ROS_BU_PKG: rb_theron_navigation
      ROS_BU_LAUNCH: default.launch.py
    network_mode: host
