---
version: "3.7"
services:
  rb-theron-sim:
    image: robotnik/rb-theron-sim:melodic-devel
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # command: "sleep infinity"
    network_mode: "host"
    stdin_open: true
    tty: true
    privileged: true
    environment:
      ROS_MASTER_URI: "http://localhost:11311"
      GAZEBO_MASTER_URI: "http://localhost:11345"
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIE: graphics
      LIBGL_ALWAYS_INDIRECT: 0
      ROS_BU_PKG: "rb_theron_sim_bringup"
      ROS_BU_LAUNCH: "rb_theron_complete.launch"
      LAUNCH_ROSBRIDGE: "true"
      USE_GPU_FOR_SIMULATION: "false"
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    devices:
      - "/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
